"use client";

import * as React from "react";
import { Check, ChevronsUpDown } from "lucide-react";
import { cn } from "~/lib/utils";
import { useMediaQuery } from "~/hooks/use-media-query";
import { Button } from "~/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "~/components/ui/command";
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "~/components/ui/drawer";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "~/components/ui/popover";

type Region = "US" | "EU" | "KR" | "TW";

const allRealms: Record<Region, { value: string; label: string }[]> = {
  US: [
    { value: "Aegwynn", label: "Aegwynn" },
    { value: "Aerie Peak", label: "Aerie Peak" },
    { value: "Agamaggan", label: "Agamaggan" },
    { value: "Aggramar", label: "Aggramar" },
    { value: "Akama", label: "Akama" },
    { value: "Alexstrasza", label: "Alexstrasza" },
    { value: "Alleria", label: "Alleria" },
    { value: "Altar of Storms", label: "Altar of Storms" },
    { value: "Alterac Mountains", label: "Alterac Mountains" },
    { value: "Aman'Thul", label: "Aman'Thul" },
    { value: "Andorhal", label: "Andorhal" },
    { value: "Anetheron", label: "Anetheron" },
    { value: "Antonidas", label: "Antonidas" },
    { value: "Anub'arak", label: "Anub'arak" },
    { value: "Anvilmar", label: "Anvilmar" },
    { value: "Arathor", label: "Arathor" },
    { value: "Archimonde", label: "Archimonde" },
    { value: "Area 52", label: "Area 52" },
    { value: "Argent Dawn", label: "Argent Dawn" },
    { value: "Arthas", label: "Arthas" },
    { value: "Arygos", label: "Arygos" },
    { value: "Auchindoun", label: "Auchindoun" },
    { value: "Azgalor", label: "Azgalor" },
    { value: "Azjol-Nerub", label: "Azjol-Nerub" },
    { value: "Azralon", label: "Azralon" },
    { value: "Azshara", label: "Azshara" },
    { value: "Azuremyst", label: "Azuremyst" },
    { value: "Baelgun", label: "Baelgun" },
    { value: "Balnazzar", label: "Balnazzar" },
    { value: "Barthilas", label: "Barthilas" },
    { value: "Black Dragonflight", label: "Black Dragonflight" },
    { value: "Blackhand", label: "Blackhand" },
    { value: "Blackrock", label: "Blackrock" },
    { value: "Blackwater Raiders", label: "Blackwater Raiders" },
    { value: "Blackwing Lair", label: "Blackwing Lair" },
    { value: "Blade's Edge", label: "Blade's Edge" },
    { value: "Bladefist", label: "Bladefist" },
    { value: "Bleeding Hollow", label: "Bleeding Hollow" },
    { value: "Blood Furnace", label: "Blood Furnace" },
    { value: "Bloodhoof", label: "Bloodhoof" },
    { value: "Bloodscalp", label: "Bloodscalp" },
    { value: "Bonechewer", label: "Bonechewer" },
    { value: "Borean Tundra", label: "Borean Tundra" },
    { value: "Boulderfist", label: "Boulderfist" },
    { value: "Bronzebeard", label: "Bronzebeard" },
    { value: "Burning Blade", label: "Burning Blade" },
    { value: "Burning Legion", label: "Burning Legion" },
    { value: "Caelestrasz", label: "Caelestrasz" },
    { value: "Cairne", label: "Cairne" },
    { value: "Cenarion Circle", label: "Cenarion Circle" },
    { value: "Cenarius", label: "Cenarius" },
    { value: "Cho'gall", label: "Cho'gall" },
    { value: "Chromaggus", label: "Chromaggus" },
    { value: "Coilfang", label: "Coilfang" },
    { value: "Crushridge", label: "Crushridge" },
    { value: "Daggerspine", label: "Daggerspine" },
    { value: "Dalaran", label: "Dalaran" },
    { value: "Dalvengyr", label: "Dalvengyr" },
    { value: "Dark Iron", label: "Dark Iron" },
    { value: "Darkspear", label: "Darkspear" },
    { value: "Darrowmere", label: "Darrowmere" },
    { value: "Dath'Remar", label: "Dath'Remar" },
    { value: "Dawnbringer", label: "Dawnbringer" },
    { value: "Deathwing", label: "Deathwing" },
    { value: "Demon Soul", label: "Demon Soul" },
    { value: "Dentarg", label: "Dentarg" },
    { value: "Destromath", label: "Destromath" },
    { value: "Dethecus", label: "Dethecus" },
    { value: "Detheroc", label: "Detheroc" },
    { value: "Doomhammer", label: "Doomhammer" },
    { value: "Draenor", label: "Draenor" },
    { value: "Dragonblight", label: "Dragonblight" },
    { value: "Dragonmaw", label: "Dragonmaw" },
    { value: "Drak'Tharon", label: "Drak'Tharon" },
    { value: "Drak'thul", label: "Drak'thul" },
    { value: "Draka", label: "Draka" },
    { value: "Drakkari", label: "Drakkari" },
    { value: "Dreadmaul", label: "Dreadmaul" },
    { value: "Drenden", label: "Drenden" },
    { value: "Dunemaul", label: "Dunemaul" },
    { value: "Durotan", label: "Durotan" },
    { value: "Duskwood", label: "Duskwood" },
    { value: "Earthen Ring", label: "Earthen Ring" },
    { value: "Echo Isles", label: "Echo Isles" },
    { value: "Eitrigg", label: "Eitrigg" },
    { value: "Eldre'Thalas", label: "Eldre'Thalas" },
    { value: "Elune", label: "Elune" },
    { value: "Emerald Dream", label: "Emerald Dream" },
    { value: "Eonar", label: "Eonar" },
    { value: "Eredar", label: "Eredar" },
    { value: "Executus", label: "Executus" },
    { value: "Exodar", label: "Exodar" },
    { value: "Farstriders", label: "Farstriders" },
    { value: "Feathermoon", label: "Feathermoon" },
    { value: "Fenris", label: "Fenris" },
    { value: "Firetree", label: "Firetree" },
    { value: "Fizzcrank", label: "Fizzcrank" },
    { value: "Frostmane", label: "Frostmane" },
    { value: "Frostmourne", label: "Frostmourne" },
    { value: "Frostwolf", label: "Frostwolf" },
    { value: "Galakrond", label: "Galakrond" },
    { value: "Gallywix", label: "Gallywix" },
    { value: "Garithos", label: "Garithos" },
    { value: "Garona", label: "Garona" },
    { value: "Garrosh", label: "Garrosh" },
    { value: "Ghostlands", label: "Ghostlands" },
    { value: "Gilneas", label: "Gilneas" },
    { value: "Gnomeregan", label: "Gnomeregan" },
    { value: "Goldrinn", label: "Goldrinn" },
    { value: "Gorefiend", label: "Gorefiend" },
    { value: "Gorgonnash", label: "Gorgonnash" },
    { value: "Greymane", label: "Greymane" },
    { value: "Grizzly Hills", label: "Grizzly Hills" },
    { value: "Gul'dan", label: "Gul'dan" },
    { value: "Gundrak", label: "Gundrak" },
    { value: "Gurubashi", label: "Gurubashi" },
    { value: "Hakkar", label: "Hakkar" },
    { value: "Haomarush", label: "Haomarush" },
    { value: "Hellscream", label: "Hellscream" },
    { value: "Hydraxis", label: "Hydraxis" },
    { value: "Hyjal", label: "Hyjal" },
    { value: "Icecrown", label: "Icecrown" },
    { value: "Illidan", label: "Illidan" },
    { value: "Jaedenar", label: "Jaedenar" },
    { value: "Jubei'Thos", label: "Jubei'Thos" },
    { value: "Kael'thas", label: "Kael'thas" },
    { value: "Kalecgos", label: "Kalecgos" },
    { value: "Kargath", label: "Kargath" },
    { value: "Kel'Thuzad", label: "Kel'Thuzad" },
    { value: "Khadgar", label: "Khadgar" },
    { value: "Khaz Modan", label: "Khaz Modan" },
    { value: "Khaz'goroth", label: "Khaz'goroth" },
    { value: "Kil'jaeden", label: "Kil'jaeden" },
    { value: "Kilrogg", label: "Kilrogg" },
    { value: "Kirin Tor", label: "Kirin Tor" },
    { value: "Korgath", label: "Korgath" },
    { value: "Korialstrasz", label: "Korialstrasz" },
    { value: "Kul Tiras", label: "Kul Tiras" },
    { value: "Laughing Skull", label: "Laughing Skull" },
    { value: "Lethon", label: "Lethon" },
    { value: "Lightbringer", label: "Lightbringer" },
    { value: "Lightning's Blade", label: "Lightning's Blade" },
    { value: "Lightninghoof", label: "Lightninghoof" },
    { value: "Llane", label: "Llane" },
    { value: "Lothar", label: "Lothar" },
    { value: "Madoran", label: "Madoran" },
    { value: "Maelstrom", label: "Maelstrom" },
    { value: "Magtheridon", label: "Magtheridon" },
    { value: "Maiev", label: "Maiev" },
    { value: "Mal'Ganis", label: "Mal'Ganis" },
    { value: "Malfurion", label: "Malfurion" },
    { value: "Malorne", label: "Malorne" },
    { value: "Malygos", label: "Malygos" },
    { value: "Mannoroth", label: "Mannoroth" },
    { value: "Medivh", label: "Medivh" },
    { value: "Misha", label: "Misha" },
    { value: "Mok'Nathal", label: "Mok'Nathal" },
    { value: "Moon Guard", label: "Moon Guard" },
    { value: "Moonrunner", label: "Moonrunner" },
    { value: "Mug'thol", label: "Mug'thol" },
    { value: "Muradin", label: "Muradin" },
    { value: "Nagrand", label: "Nagrand" },
    { value: "Nathrezim", label: "Nathrezim" },
    { value: "Nazgrel", label: "Nazgrel" },
    { value: "Nazjatar", label: "Nazjatar" },
    { value: "Nemesis", label: "Nemesis" },
    { value: "Ner'zhul", label: "Ner'zhul" },
    { value: "Nesingwary", label: "Nesingwary" },
    { value: "Nordrassil", label: "Nordrassil" },
    { value: "Norgannon", label: "Norgannon" },
    { value: "Onyxia", label: "Onyxia" },
    { value: "Perenolde", label: "Perenolde" },
    { value: "Proudmoore", label: "Proudmoore" },
    { value: "Quel'Thalas", label: "Quel'Thalas" },
    { value: "Quel'dorei", label: "Quel'dorei" },
    { value: "Ragnaros", label: "Ragnaros" },
    { value: "Ravencrest", label: "Ravencrest" },
    { value: "Ravenholdt", label: "Ravenholdt" },
    { value: "Rexxar", label: "Rexxar" },
    { value: "Rivendare", label: "Rivendare" },
    { value: "Runetotem", label: "Runetotem" },
    { value: "Sargeras", label: "Sargeras" },
    { value: "Saurfang", label: "Saurfang" },
    { value: "Scarlet Crusade", label: "Scarlet Crusade" },
    { value: "Scilla", label: "Scilla" },
    { value: "Sen'jin", label: "Sen'jin" },
    { value: "Sentinels", label: "Sentinels" },
    { value: "Shadow Council", label: "Shadow Council" },
    { value: "Shadowmoon", label: "Shadowmoon" },
    { value: "Shadowsong", label: "Shadowsong" },
    { value: "Shandris", label: "Shandris" },
    { value: "Shattered Halls", label: "Shattered Halls" },
    { value: "Shattered Hand", label: "Shattered Hand" },
    { value: "Shu'halo", label: "Shu'halo" },
    { value: "Silver Hand", label: "Silver Hand" },
    { value: "Silvermoon", label: "Silvermoon" },
    { value: "Sisters of Elune", label: "Sisters of Elune" },
    { value: "Skullcrusher", label: "Skullcrusher" },
    { value: "Skywall", label: "Skywall" },
    { value: "Smolderthorn", label: "Smolderthorn" },
    { value: "Spinebreaker", label: "Spinebreaker" },
    { value: "Spirestone", label: "Spirestone" },
    { value: "Staghelm", label: "Staghelm" },
    { value: "Steamwheedle Cartel", label: "Steamwheedle Cartel" },
    { value: "Stonemaul", label: "Stonemaul" },
    { value: "Stormrage", label: "Stormrage" },
    { value: "Stormreaver", label: "Stormreaver" },
    { value: "Stormscale", label: "Stormscale" },
    { value: "Suramar", label: "Suramar" },
    { value: "Tanaris", label: "Tanaris" },
    { value: "Terenas", label: "Terenas" },
    { value: "Terokkar", label: "Terokkar" },
    { value: "Thaurissan", label: "Thaurissan" },
    { value: "The Forgotten Coast", label: "The Forgotten Coast" },
    { value: "The Scryers", label: "The Scryers" },
    { value: "The Underbog", label: "The Underbog" },
    { value: "The Venture Co", label: "The Venture Co" },
    { value: "Thorium Brotherhood", label: "Thorium Brotherhood" },
    { value: "Thrall", label: "Thrall" },
    { value: "Thunderhorn", label: "Thunderhorn" },
    { value: "Thunderlord", label: "Thunderlord" },
    { value: "Tichondrius", label: "Tichondrius" },
    { value: "Tol Barad", label: "Tol Barad" },
    { value: "Tortheldrin", label: "Tortheldrin" },
    { value: "Trollbane", label: "Trollbane" },
    { value: "Turalyon", label: "Turalyon" },
    { value: "Twisting Nether", label: "Twisting Nether" },
    { value: "Uldaman", label: "Uldaman" },
    { value: "Uldum", label: "Uldum" },
    { value: "Undermine", label: "Undermine" },
    { value: "Ursin", label: "Ursin" },
    { value: "Uther", label: "Uther" },
    { value: "Vashj", label: "Vashj" },
    { value: "Vek'nilash", label: "Vek'nilash" },
    { value: "Velen", label: "Velen" },
    { value: "Warsong", label: "Warsong" },
    { value: "Whisperwind", label: "Whisperwind" },
    { value: "Wildhammer", label: "Wildhammer" },
    { value: "Windrunner", label: "Windrunner" },
    { value: "Winterhoof", label: "Winterhoof" },
    { value: "Wyrmrest Accord", label: "Wyrmrest Accord" },
    { value: "Ysera", label: "Ysera" },
    { value: "Ysondre", label: "Ysondre" },
    { value: "Zangarmarsh", label: "Zangarmarsh" },
    { value: "Zul'jin", label: "Zul'jin" },
    { value: "Zuluhed", label: "Zuluhed" },
  ],
  EU: [
    { value: "Aegwynn", label: "Aegwynn" },
    { value: "Aerie Peak", label: "Aerie Peak" },
    { value: "Agamaggan", label: "Agamaggan" },
    { value: "Aggra (Português)", label: "Aggra (Português)" },
    { value: "Aggramar", label: "Aggramar" },
    { value: "Ahn'Qiraj", label: "Ahn'Qiraj" },
    { value: "Al'Akir", label: "Al'Akir" },
    { value: "Alexstrasza", label: "Alexstrasza" },
    { value: "Alleria", label: "Alleria" },
    { value: "Alonsus", label: "Alonsus" },
    { value: "Aman'Thul", label: "Aman'Thul" },
    { value: "Ambossar", label: "Ambossar" },
    { value: "Anachronos", label: "Anachronos" },
    { value: "Anetheron", label: "Anetheron" },
    { value: "Antonidas", label: "Antonidas" },
    { value: "Anub'arak", label: "Anub'arak" },
    { value: "Arak-arahm", label: "Arak-arahm" },
    { value: "Arathi", label: "Arathi" },
    { value: "Arathor", label: "Arathor" },
    { value: "Archimonde", label: "Archimonde" },
    { value: "Area 52", label: "Area 52" },
    { value: "Argent Dawn", label: "Argent Dawn" },
    { value: "Arthas", label: "Arthas" },
    { value: "Arygos", label: "Arygos" },
    { value: "Ashenvale", label: "Ashenvale" },
    { value: "Aszune", label: "Aszune" },
    { value: "Auchindoun", label: "Auchindoun" },
    { value: "Azjol-Nerub", label: "Azjol-Nerub" },
    { value: "Azshara", label: "Azshara" },
    { value: "Azuregos", label: "Azuregos" },
    { value: "Azuremyst", label: "Azuremyst" },
    { value: "Baelgun", label: "Baelgun" },
    { value: "Balnazzar", label: "Balnazzar" },
    { value: "Blackhand", label: "Blackhand" },
    { value: "Blackmoore", label: "Blackmoore" },
    { value: "Blackrock", label: "Blackrock" },
    { value: "Blackscar", label: "Blackscar" },
    { value: "Blade's Edge", label: "Blade's Edge" },
    { value: "Bladefist", label: "Bladefist" },
    { value: "Bloodfeather", label: "Bloodfeather" },
    { value: "Bloodhoof", label: "Bloodhoof" },
    { value: "Bloodscalp", label: "Bloodscalp" },
    { value: "Blutkessel", label: "Blutkessel" },
    { value: "Booty Bay", label: "Booty Bay" },
    { value: "Borean Tundra", label: "Borean Tundra" },
    { value: "Boulderfist", label: "Boulderfist" },
    { value: "Bronze Dragonflight", label: "Bronze Dragonflight" },
    { value: "Bronzebeard", label: "Bronzebeard" },
    { value: "Burning Blade", label: "Burning Blade" },
    { value: "Burning Legion", label: "Burning Legion" },
    { value: "Burning Steppes", label: "Burning Steppes" },
    { value: "C'Thun", label: "C'Thun" },
    { value: "Chamber of Aspects", label: "Chamber of Aspects" },
    { value: "Chants éternels", label: "Chants éternels" },
    { value: "Cho'gall", label: "Cho'gall" },
    { value: "Chromaggus", label: "Chromaggus" },
    { value: "Colinas Pardas", label: "Colinas Pardas" },
    { value: "Confrérie du Thorium", label: "Confrérie du Thorium" },
    { value: "Conseil des Ombres", label: "Conseil des Ombres" },
    { value: "Crushridge", label: "Crushridge" },
    { value: "Culte de la Rive noire", label: "Culte de la Rive noire" },
    { value: "Daggerspine", label: "Daggerspine" },
    { value: "Dalaran", label: "Dalaran" },
    { value: "Dalvengyr", label: "Dalvengyr" },
    { value: "Darkmoon Faire", label: "Darkmoon Faire" },
    { value: "Darksorrow", label: "Darksorrow" },
    { value: "Darkspear", label: "Darkspear" },
    { value: "Das Konsortium", label: "Das Konsortium" },
    { value: "Das Syndikat", label: "Das Syndikat" },
    { value: "Deathguard", label: "Deathguard" },
    { value: "Deathweaver", label: "Deathweaver" },
    { value: "Deathwing", label: "Deathwing" },
    { value: "Deepholm", label: "Deepholm" },
    { value: "Defias Brotherhood", label: "Defias Brotherhood" },
    { value: "Dentarg", label: "Dentarg" },
    { value: "Der Mithrilorden", label: "Der Mithrilorden" },
    { value: "Der Rat von Dalaran", label: "Der Rat von Dalaran" },
    { value: "Der abyssische Rat", label: "Der abyssische Rat" },
    { value: "Destromath", label: "Destromath" },
    { value: "Dethecus", label: "Dethecus" },
    { value: "Die Aldor", label: "Die Aldor" },
    { value: "Die Arguswacht", label: "Die Arguswacht" },
    { value: "Die Nachtwache", label: "Die Nachtwache" },
    { value: "Die Silberne Hand", label: "Die Silberne Hand" },
    { value: "Die Todeskrallen", label: "Die Todeskrallen" },
    { value: "Die ewige Wacht", label: "Die ewige Wacht" },
    { value: "Doomhammer", label: "Doomhammer" },
    { value: "Draenor", label: "Draenor" },
    { value: "Dragonblight", label: "Dragonblight" },
    { value: "Dragonmaw", label: "Dragonmaw" },
    { value: "Drak'thul", label: "Drak'thul" },
    { value: "Drek'Thar", label: "Drek'Thar" },
    { value: "Dun Modr", label: "Dun Modr" },
    { value: "Dun Morogh", label: "Dun Morogh" },
    { value: "Dunemaul", label: "Dunemaul" },
    { value: "Durotan", label: "Durotan" },
    { value: "Earthen Ring", label: "Earthen Ring" },
    { value: "Echsenkessel", label: "Echsenkessel" },
    { value: "Eitrigg", label: "Eitrigg" },
    { value: "Eldre'Thalas", label: "Eldre'Thalas" },
    { value: "Elune", label: "Elune" },
    { value: "Emerald Dream", label: "Emerald Dream" },
    { value: "Emeriss", label: "Emeriss" },
    { value: "Eonar", label: "Eonar" },
    { value: "Eredar", label: "Eredar" },
    { value: "Eversong", label: "Eversong" },
    { value: "Executus", label: "Executus" },
    { value: "Exodar", label: "Exodar" },
    { value: "Festung der Stürme", label: "Festung der Stürme" },
    { value: "Fordragon", label: "Fordragon" },
    { value: "Forscherliga", label: "Forscherliga" },
    { value: "Frostmane", label: "Frostmane" },
    { value: "Frostmourne", label: "Frostmourne" },
    { value: "Frostwhisper", label: "Frostwhisper" },
    { value: "Frostwolf", label: "Frostwolf" },
    { value: "Galakrond", label: "Galakrond" },
    { value: "Garona", label: "Garona" },
    { value: "Garrosh", label: "Garrosh" },
    { value: "Genjuros", label: "Genjuros" },
    { value: "Ghostlands", label: "Ghostlands" },
    { value: "Gilneas", label: "Gilneas" },
    { value: "Goldrinn", label: "Goldrinn" },
    { value: "Gordunni", label: "Gordunni" },
    { value: "Gorgonnash", label: "Gorgonnash" },
    { value: "Greymane", label: "Greymane" },
    { value: "Grim Batol", label: "Grim Batol" },
    { value: "Grom", label: "Grom" },
    { value: "Gul'dan", label: "Gul'dan" },
    { value: "Hakkar", label: "Hakkar" },
    { value: "Haomarush", label: "Haomarush" },
    { value: "Hellfire", label: "Hellfire" },
    { value: "Hellscream", label: "Hellscream" },
    { value: "Howling Fjord", label: "Howling Fjord" },
    { value: "Hyjal", label: "Hyjal" },
    { value: "Illidan", label: "Illidan" },
    { value: "Jaedenar", label: "Jaedenar" },
    { value: "Kael'thas", label: "Kael'thas" },
    { value: "Karazhan", label: "Karazhan" },
    { value: "Kargath", label: "Kargath" },
    { value: "Kazzak", label: "Kazzak" },
    { value: "Kel'Thuzad", label: "Kel'Thuzad" },
    { value: "Khadgar", label: "Khadgar" },
    { value: "Khaz Modan", label: "Khaz Modan" },
    { value: "Khaz'goroth", label: "Khaz'goroth" },
    { value: "Kil'jaeden", label: "Kil'jaeden" },
    { value: "Kilrogg", label: "Kilrogg" },
    { value: "Kirin Tor", label: "Kirin Tor" },
    { value: "Kor'gall", label: "Kor'gall" },
    { value: "Krag'jin", label: "Krag'jin" },
    { value: "Krasus", label: "Krasus" },
    { value: "Kul Tiras", label: "Kul Tiras" },
    { value: "Kult der Verdammten", label: "Kult der Verdammten" },
    { value: "La Croisade écarlate", label: "La Croisade écarlate" },
    { value: "Laughing Skull", label: "Laughing Skull" },
    { value: "Les Clairvoyants", label: "Les Clairvoyants" },
    { value: "Les Sentinelles", label: "Les Sentinelles" },
    { value: "Lich King", label: "Lich King" },
    { value: "Lightbringer", label: "Lightbringer" },
    { value: "Lightning's Blade", label: "Lightning's Blade" },
    { value: "Lordaeron", label: "Lordaeron" },
    { value: "Los Errantes", label: "Los Errantes" },
    { value: "Lothar", label: "Lothar" },
    { value: "Madmortem", label: "Madmortem" },
    { value: "Magtheridon", label: "Magtheridon" },
    { value: "Mal'Ganis", label: "Mal'Ganis" },
    { value: "Malfurion", label: "Malfurion" },
    { value: "Malorne", label: "Malorne" },
    { value: "Malygos", label: "Malygos" },
    { value: "Mannoroth", label: "Mannoroth" },
    { value: "Marécage de Zangar", label: "Marécage de Zangar" },
    { value: "Mazrigos", label: "Mazrigos" },
    { value: "Medivh", label: "Medivh" },
    { value: "Minahonda", label: "Minahonda" },
    { value: "Moonglade", label: "Moonglade" },
    { value: "Mug'thol", label: "Mug'thol" },
    { value: "Nagrand", label: "Nagrand" },
    { value: "Nathrezim", label: "Nathrezim" },
    { value: "Naxxramas", label: "Naxxramas" },
    { value: "Nazjatar", label: "Nazjatar" },
    { value: "Nefarian", label: "Nefarian" },
    { value: "Nemesis", label: "Nemesis" },
    { value: "Neptulon", label: "Neptulon" },
    { value: "Ner'zhul", label: "Ner'zhul" },
    { value: "Nera'thor", label: "Nera'thor" },
    { value: "Nethersturm", label: "Nethersturm" },
    { value: "Nordrassil", label: "Nordrassil" },
    { value: "Norgannon", label: "Norgannon" },
    { value: "Nozdormu", label: "Nozdormu" },
    { value: "Onyxia", label: "Onyxia" },
    { value: "Outland", label: "Outland" },
    { value: "Perenolde", label: "Perenolde" },
    { value: "Pozzo dell'Eternità", label: "Pozzo dell'Eternità" },
    { value: "Proudmoore", label: "Proudmoore" },
    { value: "Quel'Thalas", label: "Quel'Thalas" },
    { value: "Ragnaros", label: "Ragnaros" },
    { value: "Rajaxx", label: "Rajaxx" },
    { value: "Rashgarroth", label: "Rashgarroth" },
    { value: "Ravencrest", label: "Ravencrest" },
    { value: "Ravenholdt", label: "Ravenholdt" },
    { value: "Razuvious", label: "Razuvious" },
    { value: "Rexxar", label: "Rexxar" },
    { value: "Runetotem", label: "Runetotem" },
    { value: "Sanguino", label: "Sanguino" },
    { value: "Sargeras", label: "Sargeras" },
    { value: "Saurfang", label: "Saurfang" },
    { value: "Scarshield Legion", label: "Scarshield Legion" },
    { value: "Sen'jin", label: "Sen'jin" },
    { value: "Shadowsong", label: "Shadowsong" },
    { value: "Shattered Halls", label: "Shattered Halls" },
    { value: "Shattered Hand", label: "Shattered Hand" },
    { value: "Shattrath", label: "Shattrath" },
    { value: "Shen'dralar", label: "Shen'dralar" },
    { value: "Silvermoon", label: "Silvermoon" },
    { value: "Sinstralis", label: "Sinstralis" },
    { value: "Skullcrusher", label: "Skullcrusher" },
    { value: "Soulflayer", label: "Soulflayer" },
    { value: "Spinebreaker", label: "Spinebreaker" },
    { value: "Sporeggar", label: "Sporeggar" },
    { value: "Steamwheedle Cartel", label: "Steamwheedle Cartel" },
    { value: "Stormrage", label: "Stormrage" },
    { value: "Stormreaver", label: "Stormreaver" },
    { value: "Stormscale", label: "Stormscale" },
    { value: "Sunstrider", label: "Sunstrider" },
    { value: "Suramar", label: "Suramar" },
    { value: "Sylvanas", label: "Sylvanas" },
    { value: "Taerar", label: "Taerar" },
    { value: "Talnivarr", label: "Talnivarr" },
    { value: "Tarren Mill", label: "Tarren Mill" },
    { value: "Teldrassil", label: "Teldrassil" },
    { value: "Temple noir", label: "Temple noir" },
    { value: "Terenas", label: "Terenas" },
    { value: "Terokkar", label: "Terokkar" },
    { value: "Terrordar", label: "Terrordar" },
    { value: "The Maelstrom", label: "The Maelstrom" },
    { value: "The Sha'tar", label: "The Sha'tar" },
    { value: "The Venture Co", label: "The Venture Co" },
    { value: "Theradras", label: "Theradras" },
    { value: "Thermaplugg", label: "Thermaplugg" },
    { value: "Thrall", label: "Thrall" },
    { value: "Throk'Feroth", label: "Throk'Feroth" },
    { value: "Thunderhorn", label: "Thunderhorn" },
    { value: "Tichondrius", label: "Tichondrius" },
    { value: "Tirion", label: "Tirion" },
    { value: "Todeswache", label: "Todeswache" },
    { value: "Trollbane", label: "Trollbane" },
    { value: "Turalyon", label: "Turalyon" },
    { value: "Twilight's Hammer", label: "Twilight's Hammer" },
    { value: "Twisting Nether", label: "Twisting Nether" },
    { value: "Tyrande", label: "Tyrande" },
    { value: "Uldaman", label: "Uldaman" },
    { value: "Ulduar", label: "Ulduar" },
    { value: "Uldum", label: "Uldum" },
    { value: "Un'Goro", label: "Un'Goro" },
    { value: "Varimathras", label: "Varimathras" },
    { value: "Vashj", label: "Vashj" },
    { value: "Vek'lor", label: "Vek'lor" },
    { value: "Vek'nilash", label: "Vek'nilash" },
    { value: "Vol'jin", label: "Vol'jin" },
    { value: "Wildhammer", label: "Wildhammer" },
    { value: "Wrathbringer", label: "Wrathbringer" },
    { value: "Xavius", label: "Xavius" },
    { value: "Ysera", label: "Ysera" },
    { value: "Ysondre", label: "Ysondre" },
    { value: "Zenedar", label: "Zenedar" },
    { value: "Zirkel des Cenarius", label: "Zirkel des Cenarius" },
    { value: "Zul'jin", label: "Zul'jin" },
    { value: "Zuluhed", label: "Zuluhed" },
  ],
  KR: [
    { value: "Alexstrasza", label: "Alexstrasza" },
    { value: "Azshara", label: "Azshara" },
    { value: "Burning Legion", label: "Burning Legion" },
    { value: "Cenarius", label: "Cenarius" },
    { value: "Dalaran", label: "Dalaran" },
    { value: "Deathwing", label: "Deathwing" },
    { value: "Durotan", label: "Durotan" },
    { value: "Garona", label: "Garona" },
    { value: "Gul'dan", label: "Gul'dan" },
    { value: "Hellscream", label: "Hellscream" },
    { value: "Hyjal", label: "Hyjal" },
    { value: "Malfurion", label: "Malfurion" },
    { value: "Norgannon", label: "Norgannon" },
    { value: "Rexxar", label: "Rexxar" },
    { value: "Stormrage", label: "Stormrage" },
    { value: "Wildhammer", label: "Wildhammer" },
    { value: "Windrunner", label: "Windrunner" },
    { value: "Zul'jin", label: "Zul'jin" },
  ],
  TW: [
    { value: "世界之樹", label: "世界之樹" },
    { value: "亞雷戈斯", label: "亞雷戈斯" },
    { value: "克羅之刃", label: "克羅之刃" },
    { value: "冰霜之刺", label: "冰霜之刺" },
    { value: "冰風崗哨", label: "冰風崗哨" },
    { value: "地獄吼", label: "地獄吼" },
    { value: "夜空之歌", label: "夜空之歌" },
    { value: "天空之牆", label: "天空之牆" },
    { value: "寒冰皇冠", label: "寒冰皇冠" },
    { value: "尖石", label: "尖石" },
    { value: "屠魔山谷", label: "屠魔山谷" },
    { value: "巨龍之喉", label: "巨龍之喉" },
    { value: "憤怒使者", label: "憤怒使者" },
    { value: "日落沼澤", label: "日落沼澤" },
    { value: "暗影之月", label: "暗影之月" },
    { value: "水晶之刺", label: "水晶之刺" },
    { value: "狂熱之刃", label: "狂熱之刃" },
    { value: "眾星之子", label: "眾星之子" },
    { value: "米奈希爾", label: "米奈希爾" },
    { value: "老馬布蘭契", label: "老馬布蘭契" },
    { value: "聖光之願", label: "聖光之願" },
    { value: "血之谷", label: "血之谷" },
    { value: "語風", label: "語風" },
    { value: "銀翼要塞", label: "銀翼要塞" },
    { value: "阿薩斯", label: "阿薩斯" },
    { value: "雲蛟衛", label: "雲蛟衛" },
    { value: "雷鱗", label: "雷鱗" },
  ],
};

export function RealmCombobox({
  region,
  initialRealm,
  onChange,
}: {
  region: string;
  initialRealm: string;
  onChange: (value: string) => void;
}) {
  const [open, setOpen] = React.useState(false);
  const [realm, setRealm] = React.useState(initialRealm);
  const isDesktop = useMediaQuery("(min-width: 768px)");

  const realmOptions =
    (region in allRealms ? allRealms[region as Region] : []) || [];
  if (isDesktop) {
    return (
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="outline"
            role="combobox"
            aria-expanded={open}
            className="w-full justify-between"
          >
            {realm
              ? realmOptions.find((option) => option.value === realm)?.label
              : "Select a realm"}
            <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-[200px] p-0">
          <Command>
            <CommandInput placeholder="Select a realm" />
            <CommandList>
              <CommandEmpty>No realm found.</CommandEmpty>
              <CommandGroup>
                {realmOptions.map((option) => (
                  <CommandItem
                    key={option.value}
                    value={option.value}
                    onSelect={(currentValue) => {
                      const newValue =
                        currentValue === realm ? "" : currentValue;
                      setRealm(newValue);
                      onChange(newValue); // Notify parent
                      setOpen(false);
                    }}
                  >
                    <Check
                      className={cn(
                        "mr-2 h-4 w-4",
                        realm === option.value ? "opacity-100" : "opacity-0"
                      )}
                    />
                    {option.label}
                  </CommandItem>
                ))}
              </CommandGroup>
            </CommandList>
          </Command>
        </PopoverContent>
      </Popover>
    );
  }
  return (
    <Drawer open={open} onOpenChange={setOpen}>
      <DrawerTrigger asChild className="w-full">
        <Button variant="outline">
          {realm
            ? realmOptions.find((option) => option.value === realm)?.label
            : "Select your realm"}
        </Button>
      </DrawerTrigger>
      <DrawerContent>
        <DrawerHeader className="text-left">
          <DrawerTitle>Select your realm</DrawerTitle>
          <DrawerDescription>
            Select the realm your character is on.
          </DrawerDescription>
        </DrawerHeader>
        <div>
          <Command>
            <CommandInput placeholder="Select a realm" />
            <CommandList>
              <CommandEmpty>No realm found.</CommandEmpty>
              <CommandGroup>
                {realmOptions.map((option) => (
                  <CommandItem
                    key={option.value}
                    value={option.value}
                    onSelect={(currentValue) => {
                      const newValue =
                        currentValue === realm ? "" : currentValue;
                      setRealm(newValue);
                      onChange(newValue); // Notify parent
                      setOpen(false);
                    }}
                  >
                    <Check
                      className={cn(
                        "mr-2 h-4 w-4",
                        realm === option.value ? "opacity-100" : "opacity-0"
                      )}
                    />
                    {option.label}
                  </CommandItem>
                ))}
              </CommandGroup>
            </CommandList>
          </Command>
        </div>
        <DrawerFooter>
          <DrawerClose asChild>
            <Button variant="outline">Cancel</Button>
          </DrawerClose>
        </DrawerFooter>
      </DrawerContent>
    </Drawer>
  );
}
